"""
Pytest configuration and shared fixtures for sdqctl tests.
"""

import pytest
from pathlib import Path
import tempfile


@pytest.fixture
def temp_workspace(tmp_path):
    """Create a temporary workspace with test files."""
    # Create test file structure
    (tmp_path / "lib").mkdir()
    (tmp_path / "lib" / "auth.js").write_text("// auth code\nfunction login() {}")
    (tmp_path / "lib" / "utils.js").write_text("// utils code\nfunction format() {}")
    (tmp_path / "lib" / "secret.js").write_text("// secret - should be denied")
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "auth.test.js").write_text("// auth tests")
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("# main app")
    return tmp_path


@pytest.fixture
def sample_conv_content():
    """Minimal valid .conv file content."""
    return """MODEL gpt-4
ADAPTER mock
MODE audit
PROMPT Analyze the code.
"""


@pytest.fixture
def complex_conv_content():
    """Full-featured .conv file content."""
    return """MODEL gpt-4
ADAPTER mock
MODE audit
MAX-CYCLES 2

CONTEXT @lib/*.js
CONTEXT-LIMIT 80%
ON-CONTEXT-LIMIT compact

ALLOW-FILES lib/*.js
DENY-FILES lib/secret.js

PROLOGUE Analysis date: 2026-01-20
EPILOGUE Remember to cite line numbers.

PROMPT Analyze code quality.
CHECKPOINT quality-analysis
PROMPT Generate improvement recommendations.
COMPACT findings, recommendations

HEADER # Quality Report
FOOTER ---
FOOTER Generated by sdqctl

OUTPUT-FORMAT markdown
OUTPUT-FILE reports/quality-2026-01-20.md
"""


@pytest.fixture
def multiline_conv_content():
    """Conversation file with multiline prompts."""
    return """MODEL gpt-4
ADAPTER mock

PROMPT Analyze the code structure.
  Focus on:
  - Authentication flow
  - Error handling
  - Performance concerns
PROMPT Write recommendations.
"""


@pytest.fixture
def file_restrictions_conv_content():
    """Conversation file testing file restrictions."""
    return """MODEL gpt-4
ADAPTER mock

ALLOW-FILES lib/*.js
ALLOW-FILES src/*.py
DENY-FILES lib/secret.js
DENY-FILES **/test_*.py
ALLOW-DIR lib
DENY-DIR node_modules

PROMPT Analyze allowed files.
"""


@pytest.fixture
def steps_conv_content():
    """Conversation file with various step types."""
    return """MODEL gpt-4
ADAPTER mock

PROMPT First analysis prompt.
CHECKPOINT after-analysis
PROMPT Second prompt with improvements.
COMPACT findings
RUN npm run test
PROMPT Verify test results.
"""


@pytest.fixture
def pause_conv_content():
    """Conversation file with PAUSE directive."""
    return """MODEL gpt-4
ADAPTER mock

PROMPT Analyze the authentication code.
PAUSE Review findings before proceeding
PROMPT Generate final report.
"""


# Re-export fixtures from fixtures package
pytest_plugins = ["tests.fixtures"]
